### PR TITLE
1421 Fix spacing in partnership opps on mobile

### LINKED ISSUE #1421: Fix spacing in Partnership Opportunities section of landing page on mobile
### Overview
On mobile, a hardcoded line break in the Partnership Opportunities section is causing awkward spacing on mobile:

Screen Shot 2024-06-03 at 11 20 59 PM

### Action Items
- [x] Fix spacing on mobile

### Resources 
[Design ](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=16635-23923&t=giLjpRRlmhXINWz0-4)

### PR DESCRIPTION
**Pull request by eburdekin**
Fixes #1421 

### Changes made: 
Removed hardcoded line break in en > translation.json

### Reason for changes:
Fix awkward spacing in Partnership Opportunities section of homepage on mobile

### CODE REVIEW

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
Hi @eburdekin! This does fix the weird mobile spacing, however the `\n` was being used to help style the desktop. Can you recreate that line break using styling?

What it looks like on the Live site:
Screenshot 2024-08-26 at 2 20 04 PM


And your branch:
Screenshot 2024-08-26 at 2 22 47 PM

**Comment by eburdekin** [comment]
Good call @sydneywalcoff ! Updated the styling to mimic the line break.

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
hey @eburdekin ! 

Changes look great! I have one other small thing, though.

the mobile breakpoints move the rest of the text to align left, but the partnership text stays centered. Can we have it align left with the rest of the text on the page? The title already left aligns itself.



Other than that, this looks great!

**Comment by eburdekin** [comment]
Thanks for catching @sydneywalcoff ! Fixed 🫡

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
@eburdekin Can you left align the button too? 😅 

Please && thank you!

Screenshot 2024-09-16 at 7 56 43 PM

**Comment by eburdekin** [comment]
@sydneywalcoff couple updates:
- Re-centered body text per [Figma designs](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2-36&node-type=canvas)
- Changed Partnership Opportunities header to an `h3` tag with different styling since the text alignment & font weight are different from the other section headers on mobile

**Review by sydneywalcoff — APPROVED** [review]
@eburdekin Great catch! and great work on this!

**Pull request merged**
