### PR TITLE
Adjust completion bar values - #263

### LINKED ISSUE #263: adjust the values on the completion bar
Right now the progress bar in `FormHeader.tsx` has values that are just placeholder. We need to adjust it so they make sense while progressing through the form.

Take care to note that involvement steps cause the form to have varying length.

### PR DESCRIPTION
**Pull request by sydneywalcoff**
Fixes #263 

What did you do?
- imported the involvement context from form state
- beyond that ¯\_(ツ)_/¯ but it works lol

### CODE REVIEW

**Review by aahvocado — CHANGES_REQUESTED** [review]
I'm fine with the simple +=1 checks.
One bug that is understandably confusing: If Job is unchecked - it will be replaced with the Unemployed step. So there is a +1 there no matter what. 

Other request is to see you are able to not update it constantly while they are checking different boxes. I think it's distracting and I don't want to confuse users. I think you can just display "Step 3" until after that step.

**Comment by sydneywalcoff** [comment]
@aahvocado should this merge into dev or main?

**Comment by aahvocado** [comment]
> @aahvocado should this merge into dev or main?

Ooh, dev but it's technically a different branch than when you started this work... You can use main this time around if there's conflicts

**Review by aahvocado — APPROVED** [review]
Good stuff 🔥

**Pull request merged**
