### PR TITLE
1488 Weekly Label Check 

### PR DESCRIPTION
**Pull request by hasham-qaiser**
Fixes: #1488 

### Changes Made:
Changed script file to .mjs, and removed const require Octokit statement to import Octokit. Edited YML file to pull from correct new file 

### Reason for changes:
The node version we use has a incompatibility issue with common js files and requires ES module syntax. Hence the reason for a change to the .mjs file

### CODE REVIEW

**Review by sydneywalcoff — COMMENTED** [review]
Hey @hasham-qaiser, thanks for getting this done! I have a couple questions.

_Were you able to test this?_ I don't remember creating a token for you. I assume not, (and this is totally fine), so next question: _what version of Node did you base these changes on?_ 

I _think_ you may have picked a version of Node too high. I was googling the `--experimental-modules` flag that you added to the Process Open Issues command because I'd never seen it before, wanted to learn a little about it. I'm only seeing it documented in Node 22.8, but our Actions run on Node 20.16.

I'm curious if we need it and if it breaks the command. I'm also curious about the mjs file, but it exists in Node 20, so I don't think it'll break anything.

Interested to hear your thoughts and what you learned in your research.

**Comment by hasham-qaiser** [comment]
> Hey @hasham-qaiser, thanks for getting this done! I have a couple questions.
> 
> _Were you able to test this?_ I don't remember creating a token for you. I assume not, (and this is totally fine), so next question: _what version of Node did you base these changes on?_
> 
> I _think_ you may have picked a version of Node too high. I was googling the `--experimental-modules` flag that you added to the Process Open Issues command because I'd never seen it before, wanted to learn a little about it. I'm only seeing it documented in Node 22.8, but our Actions run on Node 20.16.
> 
> I'm curious if we need it and if it breaks the command. I'm also curious about the mjs file, but it exists in Node 20, so I don't think it'll break anything.
> 
> Interested to hear your thoughts and what you learned in your research.

Hey Sydney! I didn't need a token for testing but was able to successfully test the action on my end locally. In the most recent change i made i removed the "experimental" node flag so that it doesn't interfere and is consistent with the other workflow yml files. The switch to ES module syntax (using import instead of require) was necessary because the @octokit/rest package is now distributed as an ES module. This change is not related to the Node.js version but to the package's distribution format. I had issues using the .js file so did some research and saw that .mjs could be a fix to the issue

**Review by sydneywalcoff — APPROVED** [review]
@hasham-qaiser Ran it locally and you likely did need a token, but because of how the script was written initially, the errors get hidden in the console log. That's not your problem, however. I opened a new issue to fix that. 

This looks great! Thanks for fixing this!

**Comment by sydneywalcoff** [comment]
And thank you for the write-up on what you learned! Super interesting!

**Pull request merged**
