### PR TITLE
1376 Form Error

### PR DESCRIPTION
**Pull request by hasham-qaiser**
fixes: #1376 

### Changes made:
Removed unpermitted keys and attributes in form that were causing github errors

### Reason for changes:
 error in blank issue form, should be fixed now

### CODE REVIEW

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
Looks like we still have a couple errors

Screenshot 2024-05-29 at 12 04 56 PM

To find where the errors are populating, I'm attaching a video 
[here](https://app.screencastify.com/v3/watch/fP0vhgfDEc8oIwetyvsM)

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
@hasham-qaiser Thank you for the error resolution! Small thing: some of the info is duplicated. I'm attaching a screenshot below. You can see the Preview on the same link I went you before to see the errors. 

Screenshot 2024-06-03 at 6 34 45 PM

**Comment by hasham-qaiser** [comment]
> @hasham-qaiser Thank you for the error resolution! Small thing: some of the info is duplicated. I'm attaching a screenshot below. You can see the Preview on the same link I went you before to see the errors.
> 
> Screenshot 2024-06-03 at 6 34 45 PM

woops, just removed those duplicated fields!

**Review by sydneywalcoff — CHANGES_REQUESTED** [review]
@hasham-qaiser last thing! 

Can we change the Action Item checkboxes into a text area?
Screenshot 2024-06-05 at 10 24 54 AM

**Review by sydneywalcoff — APPROVED** [review]
@hasham-qaiser thank you for knocking this out!

**Pull request merged**
