### PR TITLE
check box copy update 986

### PR DESCRIPTION
**Pull request by awellsbiz**
Issue #986 

Hello Team,

I have updated the copy for the final page check box!

Let me know if you have any questions 🙂

Anthony Wells

### CODE REVIEW

**Review by whitneywind — DISMISSED** [review]
It looks good to me! The checkbox text matches that in the issue. I do wonder if it should say "lawyer or legal clinic" instead of "lawyer legal clinic" but the original issue does have it worded the same as it is here.

**Comment by sydneywalcoff** [comment]
@SamHyler do you have any thoughts on Whitney's callout above?

**Comment by SamHyler** [comment]
YES! @whitneywind it should have "or". I double checked in Figma, and it's written correctly there (the master pages are our SOT for Content). I have no idea how it became wrong on the Github issue, I literally copy pasted the same thing everywhere....
Thanks for catching it! 

By checking this box you take full responsibility in this declaration letter, and release all association with Hack for LA. We recommend that you have a lawyer or legal clinic review this letter before you submit your application.

**Comment by sydneywalcoff** [comment]
@awellsbiz can you update the copy to 'lawyer or legal clinic'?

**Comment by awellsbiz** [comment]
Sorry, it took so long. I have just updated the copy.

**Pull request closed without merging**
